In [1]:
import numpy as np
import numpy.linalg as npl

In [2]:
c=np.array([[-20],[-30],[0],[0]])
A = np.array([[1,1,1,0],[0.1,0.2,0,1]])
b = np.array([[100],[14]])

sbfi = np.array([False,False,True,True])

## Iteracion 1

In [3]:
sbf = sbfi
r=(sbf==False)
B = np.copy(A[:,sbf])
N = np.copy(A[:,r])
cB=np.copy(c[sbf])
print('cB: ' + str(cB.T))
cN =np.copy(c[r])
print('cN: ' + str(cN.T))
BInv=npl.inv(B)
pT=cN.T-np.dot(cB.T,np.matmul(BInv,N))
index_sbf = np.argwhere(sbf).T[0]
index_r = np.argwhere(r).T[0]
xb = np.dot(BInv,b)
colN=np.argmin(pT)
y = np.dot(BInv,N[:,colN])
colB = np.argmin(xb.T[0]/y)
print('B: \r\n'+str(B))
print('N: \r\n'+str(N))
print('pT: \r\n' + str(pT))
print('Neg: ' + str(len(pT[pT<0])))
print('Col N:' + str(colN))
print('Col B:' + str(colB))
newB = np.copy(B)
newB[:,colB] = N[:,colN]
newN = np.copy(N)
newN[:,colN] = B[:,colB]
print('new B: \r\n'+str(newB))
print('new N: \r\n'+str(newN))

cB: [[0 0]]
cN: [[-20 -30]]
B: 
[[1. 0.]
 [0. 1.]]
N: 
[[1.  1. ]
 [0.1 0.2]]
pT: 
[[-20. -30.]]
Neg: 2
Col N:1
Col B:1
new B: 
[[1.  1. ]
 [0.  0.2]]
new N: 
[[1.  0. ]
 [0.1 1. ]]


## Iteracion 2

In [5]:
sbf[index_r[colN]]=True
sbf[index_sbf[colB]]=False
r=(sbf==False)
B = np.copy(newB)
N = np.copy(newN)
new_cB = np.copy(cB)
new_cB[colB,0]= cN[colN,0]
new_cN = np.copy(cN)
new_cN[colN,0]= cB[colB,0]
cB = np.copy(new_cB)
cN = np.copy(new_cN)
print('cB: ' + str(cB.T))
print('cN: ' + str(cN.T))
BInv=npl.inv(B)
pT=cN.T-np.dot(cB.T,np.matmul(BInv,N))
index_sbf = np.argwhere(sbf).T[0]
index_r = np.argwhere(r).T[0]
xb = np.dot(BInv,b)
print('xb: '+str(xb))
colN=np.argmin(pT)
y = np.dot(BInv,N[:,colN])
colB = np.argmin(xb.T[0]/y)
print('B: \r\n'+str(B))
print('N: \r\n'+str(N))
print('pT: \r\n' + str(pT))
print('Neg: ' + str(len(pT[pT<0])))
print('Col N:' + str(colN))
print('Col B:' + str(colB))
newB = np.copy(B)
newB[:,colB] = N[:,colN]
newN = np.copy(N)
newN[:,colN] = B[:,colB]
print('new B: \r\n'+str(newB))
print('new N: \r\n'+str(newN))

cB: [[-20 -30]]
cN: [[0 0]]
B: 
[[1.  1. ]
 [0.1 0.2]]
N: 
[[1. 0.]
 [0. 1.]]
pT: 
[[ 10. 100.]]
Neg: 0
Col N:0
Col B:1
new B: 
[[1.  1. ]
 [0.1 0. ]]
new N: 
[[1.  0. ]
 [0.2 1. ]]


In [6]:
xb

array([[60.],
       [40.]])