In [56]:
import numpy as np
from scipy.optimize import linprog

In [255]:
p = np.array([1,2,3]) #precios de las variedades.
#B = np.array([[0,0,0],[0,0,0]]) #matriz binaria de camas por variedad sembrada.
w = np.array([150,250,350,20,5,12,22,1000]) #capacidad de siembra de los bancos.
v = np.array([100,350,1]) # cantidades de variedades disponibles para sembrar.
n = v.shape[0] #Cantidad de variedades.
m = w.shape[0] #Cantidad de camas.
L=np.array([[0,0,0]]) #Restricciones de NO compatibilidad por variedad.

In [258]:
p.shape[0]==n and w.shape[0]==m and v.shape[0]==n and L.shape[1]==n

True

## Convertir el problema en un problema de programación lineal

Se multiplica los coeficientes de los precios para que queden negativos pues el promebla original es de maximización 

In [259]:
c=np.tile(-p,m)
c

array([-1, -2, -3, -1, -2, -3, -1, -2, -3, -1, -2, -3, -1, -2, -3, -1, -2,
       -3, -1, -2, -3, -1, -2, -3])

Restricciones asociadas a la capacidad de los bancos para la siembra

In [260]:
A = np.repeat(-w,n).reshape(-1,1).T # Restricción de siembra
A

array([[ -150,  -150,  -150,  -250,  -250,  -250,  -350,  -350,  -350,
          -20,   -20,   -20,    -5,    -5,    -5,   -12,   -12,   -12,
          -22,   -22,   -22, -1000, -1000, -1000]])

In [266]:
b = np.array(v.sum()) #Maximo de esquejes a sembrar
b

array(451)

Restricciones de igualdad asociadas a que solo se puede sembrar una variedad por cama

In [262]:
Aeq=np.zeros((m+L.shape[0],n*m))
for i in np.arange(0,m): #Se crea un restricción por cama.
    p1 = np.zeros(i*n) #Cantidad de ceros adelante segun el indice de la cama
    p2 = np.ones(n) #Cantidad de unos que representan la restriccion
    p3 = np.zeros(((m*n)-((i*n)+n))) #cantidad de ceros al final
    r = np.concatenate((p1,p2,p3))
    Aeq[i]=r
    
Aeq[m:]=np.tile(L,m) #Restricciones de NO compatibilidad de flor
Aeq

array([[1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 

In [263]:
beq = np.zeros(m+L.shape[0])
beq[:m]=np.ones(m)
beq

array([1., 1., 1., 1., 1., 1., 1., 1., 0.])

In [264]:
res = linprog(c,A_ub=A,b_ub=b,A_eq=Aeq,b_eq=beq,bounds=(0,1))
res

     con: array([-1.85740312e-12, -1.85895743e-12, -1.85762516e-12, -1.85762516e-12,
       -1.85695903e-12, -1.85740312e-12, -1.85740312e-12, -1.85762516e-12,
        0.00000000e+00])
     fun: -23.99999999925795
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([2260.])
  status: 0
 success: True
       x: array([4.86106630e-11, 1.10779831e-12, 1.00000000e+00, 4.86107002e-11,
       1.10785379e-12, 1.00000000e+00, 4.86106895e-11, 1.10789036e-12,
       1.00000000e+00, 4.86106909e-11, 1.10799079e-12, 1.00000000e+00,
       4.86106590e-11, 1.10798718e-12, 1.00000000e+00, 4.86106771e-11,
       1.10799396e-12, 1.00000000e+00, 4.86106699e-11, 1.10797521e-12,
       1.00000000e+00, 4.86105898e-11, 1.10746373e-12, 1.00000000e+00])

In [265]:
res.x.reshape(m,n)

array([[4.86106630e-11, 1.10779831e-12, 1.00000000e+00],
       [4.86107002e-11, 1.10785379e-12, 1.00000000e+00],
       [4.86106895e-11, 1.10789036e-12, 1.00000000e+00],
       [4.86106909e-11, 1.10799079e-12, 1.00000000e+00],
       [4.86106590e-11, 1.10798718e-12, 1.00000000e+00],
       [4.86106771e-11, 1.10799396e-12, 1.00000000e+00],
       [4.86106699e-11, 1.10797521e-12, 1.00000000e+00],
       [4.86105898e-11, 1.10746373e-12, 1.00000000e+00]])