In [7]:
import numpy as np
import numpy.linalg as npl

## Problema Inicial

In [8]:
c=np.array([[-20],[-30],[0],[0]])
A = np.array([[1,1,1,0],[0.1,0.2,0,1]])
b = np.array([[100],[14]])

sbfi = np.array([False,False,True,True])

In [9]:
sbf = sbfi
r=(sbf==False)
B = np.copy(A[:,sbf])
N = np.copy(A[:,r])
cB=np.copy(c[sbf])
cN=np.copy(c[r])
BInv=npl.inv(B)
pT=cN.T-np.dot(cB.T,np.matmul(BInv,N))
index_sbf = np.argwhere(sbf).T[0]
index_r = np.argwhere(r).T[0]
print('------- ITERATION : 0 ---------')
print('B: \r\n'+str(B))
print('N: \r\n'+str(N))
itera = 1
while(len(pT[pT<0]) > 0):
    xb = np.dot(BInv,b)
    print('xb: \r\n' + str(xb))
    print('----------------')
    colN=np.argmin(pT)
    y = np.dot(BInv,N[:,colN])
    colB = np.argmin(xb.T[0]/y)
    newB = np.copy(B)
    newB[:,colB] = N[:,colN]
    newN = np.copy(N)
    newN[:,colN] = B[:,colB]
    B = np.copy(newB)
    N = np.copy(newN)
    print('------- ITERATION : '+str(itera)+' ---------')
    print('B: \r\n'+str(B))
    print('N: \r\n'+str(N))
    sbf[index_r[colN]]=True
    sbf[index_sbf[colB]]=False
    r=(sbf==False)
    new_cB = np.copy(cB)
    new_cB[colB,0]= cN[colN,0]
    new_cN = np.copy(cN)
    new_cN[colN,0]= cB[colB,0]
    cB = np.copy(new_cB)
    cN = np.copy(new_cN)
    BInv=npl.inv(B)
    pT=cN.T-np.dot(cB.T,np.matmul(BInv,N))
    index_sbf = np.argwhere(sbf).T[0]
    index_r = np.argwhere(r).T[0]
    itera=itera+1
print('xb: \r\n' + str(xb))
print('--------END--------')

------- ITERATION : 0 ---------
B: 
[[1. 0.]
 [0. 1.]]
N: 
[[1.  1. ]
 [0.1 0.2]]
xb: 
[[100.]
 [ 14.]]
----------------
------- ITERATION : 1 ---------
B: 
[[1.  1. ]
 [0.  0.2]]
N: 
[[1.  0. ]
 [0.1 1. ]]
xb: 
[[30.]
 [70.]]
----------------
------- ITERATION : 2 ---------
B: 
[[1.  1. ]
 [0.1 0.2]]
N: 
[[1. 0.]
 [0. 1.]]
xb: 
[[30.]
 [70.]]
--------END--------
