# Punto 2

![123](images/punto2.png "ab")

In [1]:
import numpy as np
import optimization.simplex as opt_s

In [2]:
c=np.array([[-15000],[-17000],[0],[0],[0]])
A = np.array([[1,-1,1,0,0],[-1,1,0,1,0],[1,1,0,0,1]])
b = np.array([[-8],[-6],[40]])

sbfi = np.array([True,True,True,False,False])
opt_s.optimize_simplex(c,A,b,sbfi)

------- ITERATION : 0 ---------
B: 
[[ 1 -1  1]
 [-1  1  0]
 [ 1  1  0]]
N: 
[[0 0]
 [1 0]
 [0 1]]
pT: 
[[ 1000. 16000.]]
x: 
[1 2 3]
xb: 
[[ 23.]
 [ 17.]
 [-14.]]
Z: -634000.0
--------END--------
